from __future__ import annotations

from typing import Dict, List

from cookbook_models import Nutrient, Recipe, SectionStyle

NDB: Dict[str, Nutrient] = {
    "hvedemel": Nutrient(364, 10.0, 76.0, 1.0),
    "rugmel": Nutrient(338, 10.3, 60.7, 1.7),
    "rugkerner": Nutrient(331, 9.5, 62.0, 1.8),
    "boghvedemel": Nutrient(343, 13.3, 71.5, 3.4),
    "grahamsmel": Nutrient(340, 13.0, 67.0, 2.5),
    "surdej": Nutrient(182, 5.0, 38.0, 0.5),
    "gær": Nutrient(105, 8.0, 8.0, 1.0),
    "salt": Nutrient(0, 0, 0, 0),
    "vand": Nutrient(0, 0, 0, 0),
    "oksekød_10": Nutrient(250, 26, 0, 17),
    "oksekød_5": Nutrient(210, 27, 0, 10),
    "hakket_svin": Nutrient(250, 17, 0, 20),
    "hakket_svin_10": Nutrient(182, 18, 0, 10),
    "bacon": Nutrient(320, 17, 1, 28),
    "svinenakke": Nutrient(270, 18, 0, 22),
    "and": Nutrient(337, 19, 0, 28),
    "kartoffel": Nutrient(77, 2, 17, 0.1),
    "blomkål": Nutrient(25, 1.9, 5.0, 0.3),
    "gulerod": Nutrient(41, 0.9, 10, 0.2),
    "løg": Nutrient(40, 1.1, 9.3, 0.1),
    "skalotteløg": Nutrient(72, 2.5, 16.8, 0.1),
    "hvidløg": Nutrient(149, 6.4, 33, 0.5),
    "tomatpuré": Nutrient(82, 4.3, 19, 0.5),
    "paprika": Nutrient(282, 14, 54, 13),
    "hakkede_tomater": Nutrient(29, 1.2, 4.8, 0.2),
    "oregano": Nutrient(265, 9, 69, 4.3),
    "basilikum": Nutrient(251, 23, 47, 4.1),
    "olivenolie": Nutrient(884, 0, 0, 100),
    "smør": Nutrient(717, 0.9, 0.1, 81),
    "mælk_15": Nutrient(46, 3.5, 4.8, 1.5),
    "mælk_35": Nutrient(64, 3.4, 4.8, 3.5),
    "fløde_38": Nutrient(366, 2.1, 2.8, 38),
    "græsk_yoghurt_10": Nutrient(133, 3.5, 3.8, 10),
    "skyr": Nutrient(63, 11, 4, 0.2),
    "æg": Nutrient(143, 12.5, 1.1, 10),
    "lasagneplader": Nutrient(360, 12, 72, 1.5),
    "pasta_tør": Nutrient(360, 12, 72, 1.5),
    "hytteost": Nutrient(81, 12, 3, 1.5),
    "parmesan": Nutrient(431, 38, 4, 29),
    "revet_ost_13": Nutrient(250, 30, 1, 13),
    "mozzarella": Nutrient(280, 22, 2, 20),
    "tommes_de_savoir": Nutrient(280, 22, 2, 20),
    "cheddar": Nutrient(403, 25, 1.3, 33),
    "parmaskinke": Nutrient(269, 28, 0, 18),
    "mornaysauce": Nutrient(160, 6, 8, 11),
    "hvid_fisk": Nutrient(82, 18, 0, 0.7),
    "spinat": Nutrient(23, 2.9, 1.4, 0.4),
    "agurk": Nutrient(15, 0.7, 2.8, 0.1),
    "citron": Nutrient(29, 1.1, 9.3, 0.3),
    "ris_tør": Nutrient(360, 7, 79, 0.7),
    "rapsolie": Nutrient(884, 0, 0, 100),
    "worcestershire": Nutrient(78, 0.7, 19, 0.2),
    "rødvin": Nutrient(85, 0.1, 2.6, 0),
    "champignon": Nutrient(22, 3.1, 3.3, 0.3),
    "østershatte": Nutrient(33, 3.3, 6.1, 0.4),
    "peberfrugt": Nutrient(31, 1, 6, 0.3),
    "havregryn": Nutrient(372, 13.2, 60, 7),
    "hakket_kylling": Nutrient(160, 21, 0, 8),
    "fiskekraft": Nutrient(10, 1, 1, 0),
    "rejer": Nutrient(99, 24, 0.2, 0.3),
    "blåmuslinger": Nutrient(86, 12, 4, 2),
    "bladselleri": Nutrient(16, 0.7, 3, 0.2),
    "hvidvin": Nutrient(82, 0.1, 2.6, 0),
    "majsstivelse": Nutrient(381, 0.3, 91, 0.1),
    "solsikkekerner": Nutrient(584, 20.8, 11.4, 51.5),
    "sukker": Nutrient(400, 0, 100, 0),
    "mørk_sirup": Nutrient(310, 0, 77, 0),
    "brun_farin": Nutrient(380, 0, 98, 0),
    "æble": Nutrient(52, 0.3, 14, 0.2),
    "cidereddike": Nutrient(21, 0, 0.9, 0),
    "æblejuice": Nutrient(46, 0.1, 11, 0.1),
    "minimælk": Nutrient(37, 3.4, 4.7, 0.5),
    "flødeost_urter": Nutrient(250, 6, 3, 24),
    "kyllingebryst": Nutrient(107, 22, 0, 2.4),
    "kokosmælk": Nutrient(177, 1.8, 2.7, 18),
    "kærnemælk": Nutrient(37, 3.5, 4.7, 0.5),
    "sigtemel": Nutrient(330, 11, 67, 1.5),
    "havremælk": Nutrient(45, 0.9, 8.0, 1.5),
    "ananas": Nutrient(50, 0.5, 13, 0.1),
}

DISPLAY_NAMES = {
    "surdej": "Surdej",
    "gær": "Gær",
    "hvedemel": "Hvedemel",
    "rugmel": "Rugmel",
    "rugkerner": "Rugkerner",
    "boghvedemel": "Boghvedemel",
    "grahamsmel": "Grahamsmel",
    "salt": "Salt",
    "vand": "Vand",
    "oksekød_10": "Hakket oksekød 10 %",
    "oksekød_5": "Hakket oksekød 5 %",
    "hakket_svin": "Hakket svinekød",
    "hakket_svin_10": "Hakket svinekød 10 %",
    "bacon": "Bacon",
    "svinenakke": "Svinenakke",
    "and": "And",
    "kartoffel": "Kartoffel",
    "blomkål": "Blomkål",
    "gulerod": "Gulerod",
    "løg": "Løg",
    "skalotteløg": "Skalotteløg",
    "hvidløg": "Hvidløg",
    "tomatpuré": "Tomatpuré",
    "paprika": "Paprika",
    "hakkede_tomater": "Hakkede tomater",
    "oregano": "Oregano",
    "basilikum": "Basilikum",
    "olivenolie": "Olivenolie",
    "smør": "Smør",
    "mælk_15": "Letmælk",
    "mælk_35": "Sødmælk",
    "fløde_38": "Piskefløde",
    "græsk_yoghurt_10": "Græsk yoghurt 10 %",
    "skyr": "Skyr",
    "æg": "Æg",
    "lasagneplader": "Lasagneplader",
    "pasta_tør": "Tør pasta",
    "hytteost": "Hytteost",
    "parmesan": "Parmesan",
    "revet_ost_13": "Revet ost 13 %",
    "mozzarella": "Mozzarella",
    "tommes_de_savoir": "Tommes de Savoir",
    "cheddar": "Cheddar",
    "parmaskinke": "Parmaskinke",
    "mornaysauce": "Mornaysauce",
    "hvid_fisk": "Hvid fisk",
    "spinat": "Spinat",
    "agurk": "Agurk",
    "citron": "Citron",
    "ris_tør": "Tørre ris",
    "rapsolie": "Rapsolie",
    "worcestershire": "Worcestershire sauce",
    "rødvin": "Rødvin",
    "champignon": "Champignon",
    "østershatte": "Østershatte",
    "peberfrugt": "Peberfrugt",
    "havregryn": "Havregryn",
    "hakket_kylling": "Hakket kylling",
    "fiskekraft": "Fiskekraft",
    "rejer": "Rejer",
    "blåmuslinger": "Blåmuslinger",
    "bladselleri": "Bladselleri",
    "hvidvin": "Hvidvin",
    "majsstivelse": "Majsstivelse",
    "solsikkekerner": "Solsikkekerner",
    "sukker": "Sukker",
    "mørk_sirup": "Mørk sirup",
    "brun_farin": "Brun farin",
    "æble": "Æble",
    "cidereddike": "Æblecidereddike",
    "æblejuice": "Æblejuice",
    "minimælk": "Minimælk",
    "flødeost_urter": "Flødeost med hvidløg og urter",
    "kyllingebryst": "Kyllingebryst",
    "kokosmælk": "Kokosmælk",
    "kærnemælk": "Kærnemælk",
    "sigtemel": "Sigtemel",
    "havremælk": "Havremælk / plantemælk",
    "ananas": "Ananas",
}

SECTION_STYLES = {
    "Bagværk": SectionStyle("#38261d", "#f5ede4", "#c87f4f", "#e6d2be"),
    "Tilbehør": SectionStyle("#18332b", "#edf5f0", "#5d8f77", "#d5e6dc"),
    "Aftensmad": SectionStyle("#2f1f17", "#f8eee8", "#bf6845", "#eed1c3"),
    "Weekend": SectionStyle("#1d2530", "#edf1f6", "#7288a4", "#d5ddea"),
}

RECIPE_SECTION_SIZE = 32
RECIPE_TITLE_SIZE = 70
RECIPE_CHIP_SIZE = 36
RECIPE_BODY_SIZE = 42
RECIPE_BODY_BOLD_SIZE = 44
RECIPE_SMALL_SIZE = 36
COMPONENT_PREFIX = ":: "
COMPONENT_TOP_GAP = 1.1
COMPONENT_BOTTOM_GAP = 0.14


RECIPES: List[Recipe] = [
    Recipe(
        section="Bagværk",
        title="Brød i stegeso",
        servings=1,
        finished_weight_g=760,
        ingredients=[
            "500 g hvedemel",
            "15 g frisk gær eller 7 g tørgær",
            "10 g fint salt",
            "3,5 dl koldt vand",
        ],
        method=[
            "Rør mel, gær, salt og vand sammen til en klistret dej. Dejen skal ikke æltes.",
            "Dæk skålen til, og lad dejen hæve 10-12 timer ved stuetemperatur.",
            "Sæt stegesoen uden låg i ovnen, og forvarm til 250 °C i 30 minutter.",
            "Hæld dejen ud på et let meldrysset bord, fold den et par gange, og lad den hvile 15 minutter.",
            "Læg dejen i den varme stegeso, sæt låg på, og bag 30 minutter.",
            "Fjern låget, og bag yderligere 12-15 minutter, til skorpen er mørk og sprød.",
            "Lad brødet køle helt af på rist før udskæring.",
        ],
        nutrient_items=[("hvedemel", 500), ("gær", 15)],
    ),
    Recipe(
        section="Bagværk",
        title="Kanelsnegle",
        servings=12,
        finished_weight_g=1300,
        ingredients=[
            "50 g gær",
            "2,5 dl lun sødmælk",
            "75 g smør, smeltet",
            "1 æg",
            "75 g sukker",
            "1/2 tsk fint salt",
            "ca. 500 g hvedemel",
            "100 g smør, 100 g brun farin, 2 spsk kanel",
            "Flormelis og lidt vand eller citronsaft, valgfrit",
        ],
        method=[
            "Rør gæren ud i den lune mælk. Tilsæt sukker, salt, æg og smeltet smør.",
            "Rør melet i lidt ad gangen, og ælt dejen 8-10 minutter, til den er glat og smidig.",
            "Lad dejen hæve tildækket 1 time, til den er tydeligt hævet.",
            "Rør fyldet sammen. Rul dejen ud til et rektangel på cirka 40 x 30 cm, og smør fyldet jævnt ud.",
            "Rul dejen stramt sammen fra den lange side, og skær 12 snegle.",
            "Sæt sneglene på bageplade eller i form, og lad dem efterhæve 30 minutter.",
            "Bag ved 200 °C i 12-15 minutter, til de er gyldne. Afkøl let, og pynt eventuelt med glasur.",
        ],
        nutrient_items=[
            ("gær", 50),
            ("mælk_35", 250),
            ("smør", 175),
            ("æg", 55),
            ("sukker", 75),
            ("hvedemel", 500),
            ("brun_farin", 100),
        ],
    ),
    Recipe(
        section="Bagværk",
        title="Surdejsbrød",
        servings=1,
        finished_weight_g=1150,
        ingredients=[
            "200 g aktiv surdej",
            "200 g grahamsmel",
            "400 g hvedemel",
            "1 g gær",
            "15 g fint salt",
            "450 g vand",
            "Solsikkeolie til fad",
        ],
        method=[
            "Bland surdej, gær, mel og vand i røremaskinens skål. Kør dejen 8 minutter ved høj hastighed.",
            "Tilsæt salt, og kør videre cirka 2 minutter, til dejen slipper skålen.",
            "Hæld dejen i et lerfad, der er smurt let med solsikkeolie.",
            "Stræk og fold dejen 3-4 gange med 30 minutters mellemrum.",
            "Sæt dejen på køl natten over, cirka 10-14 timer.",
            "Tag dejen ud cirka 2 timer før bagning, og form den til ét brød eller til boller.",
            "Forvarm ovnen til 250 °C. Hæld 1 kop vand ind i den varme ovn lige før bagning, så der dannes damp.",
            "Bag boller i cirka 18 minutter. Bag et stort brød i cirka 38 minutter, tildækket med sølvpapir indtil de sidste 10 minutter.",
            "Lad brødet køle helt af på rist før udskæring.",
        ],
        nutrient_items=[("surdej", 200), ("grahamsmel", 200), ("hvedemel", 400), ("gær", 1)],
    ),
    Recipe(
        section="Bagværk",
        title="Rugbrød",
        servings=2,
        finished_weight_g=3000,
        ingredients=[
            "200 g aktiv rugsurdej",
            "1 l lunkent vand",
            "3 spsk fint salt (ca. 45 g)",
            "1 tsk sukker",
            "400 g knækkede rugkerner",
            "100 g rugmel",
            "500 g hvedemel",
            "3,5 dl lunkent vand",
            "665 g rugmel",
            "1 dl solsikkekerner",
            "1-2 spsk mørk sirup",
            "Neutral olie til 2 forme og pensling",
        ],
        method=[
            "Rør surdej, 1 l lunkent vand, salt og sukker sammen i en stor skål, til surdejen er opløst.",
            "Tilsæt rugkerner, 100 g rugmel og hvedemel, og rør dejen godt sammen.",
            "Dæk skålen med et rent viskestykke, og lad dejen stå ved stuetemperatur i 24 timer.",
            "Rør 3,5 dl lunkent vand, 665 g rugmel, solsikkekerner og sirup i dejen dagen efter.",
            "Rør dejen grundigt, til den har konsistens som en sej grød.",
            "Tag cirka 1 kop dej fra som surdej til næste bagning, drys toppen med lidt salt, dæk skålen til, og opbevar den i køleskab. Vent cirka 1 uge, før den bruges igen.",
            "Fordel dejen i 2 smurte rugbrødsforme, og glat overfladen med en våd dejskraber eller ske.",
            "Lad brødene hæve 4 timer ved stuetemperatur.",
            "Pensl toppen let med olie, og bag rugbrødene ved 190 °C i cirka 1½ time.",
            "Pensl de varme skorper med olie, tag brødene ud af formene, og lad dem køle af under et viskestykke.",
        ],
        nutrient_items=[
            ("surdej", 200),
            ("vand", 1350),
            ("salt", 45),
            ("sukker", 4),
            ("rugkerner", 400),
            ("rugmel", 765),
            ("hvedemel", 500),
            ("solsikkekerner", 60),
            ("mørk_sirup", 30),
        ],
    ),
    Recipe(
        section="Bagværk",
        title="Sigtebrød",
        servings=2,
        finished_weight_g=1470,
        ingredients=[
            "50 g gær",
            "3 dl koldt vand",
            "4 dl kærnemælk",
            "30 g smør, smeltet",
            "2 tsk fint salt",
            "700 g sigtemel",
            "ca. 300 g hvedemel",
            "Sammenpisket æg, mælk eller vand til pensling",
        ],
        method=[
            "Rør gæren ud i vand og kærnemælk i en røreskål.",
            "Smelt smørret og lad det køle lidt af. Tilsæt det til dejen sammen med salt, sigtemel og hvedemel.",
            "Ælt dejen grundigt i 8-10 minutter, til den er glat og smidig.",
            "Dæk skålen til og lad dejen hæve lunt i ca. 1 time, til den er tydeligt hævet.",
            "Slå dejen ned, del den i to og form hvert stykke til et aflangt brød.",
            "Læg brødene på en bageplade med bagepapir og lad dem efterhæve i 30 minutter.",
            "Rids brødene med en skarp kniv og pensl med sammenpisket æg, mælk eller vand.",
            "Bag ved 200 °C i 30-35 minutter, til brødene er gyldne og hule, når man banker let på undersiden.",
            "Lad brødene køle af på rist inden udskæring.",
        ],
        nutrient_items=[
            ("gær", 50),
            ("kærnemælk", 400),
            ("smør", 30),
            ("sigtemel", 700),
            ("hvedemel", 300),
        ],
        tags=["Jul"],
    ),
    Recipe(
        section="Bagværk",
        title="Morgenmadsvafler",
        servings=2,
        finished_weight_g=480,
        ingredients=[
            ":: Vaflerne",
            "150 g havregryn",
            "3 dl plantemælk (rismælk eller havremælk)",
            "2 æg",
            "1 tsk vaniljepulver",
            "Kokosolie til vaffeljernet",
            ":: Servering",
            "Sirup",
            "Rosiner",
            "Frisk frugt",
        ],
        method=[
            "Blend havregrynene til mel i en minihakker eller blender.",
            "Pisk havregrynsmel, plantemælk, æg og vaniljepulver godt sammen til en ensartet dej.",
            "Varm vaffeljernet op til niveau 6 (eller højt). Smør begge sider med kokosolie og luk jernet. Vent til det er gennemvarmt.",
            "Hæld dej på jernet — ca. halvdelen ad gangen — og bag vaflerne i 3-4 minutter, til de er gyldne og sprøde.",
            "Gentag med den resterende dej.",
            "Server straks med valgfri topping, fx sirup, rosiner eller frisk frugt.",
        ],
        nutrient_items=[
            ("havregryn", 150),
            ("havremælk", 300),
            ("æg", 110),
        ],
    ),
    Recipe(
        section="Tilbehør",
        title="Mini hash browns",
        servings=4,
        finished_weight_g=420,
        ingredients=[
            "400 g bagekartofler, groftrevet",
            "1 spsk majsstivelse",
            "1 tsk hvidløgspulver",
            "1 tsk løgpulver",
            "1/2 tsk paprika",
            "Salt og friskkværnet peber",
            "2 spsk neutral olie",
        ],
        method=[
            "Læg de revne kartofler i koldt vand i 5 minutter, og pres dem derefter helt tørre i et rent viskestykke.",
            "Bland kartoflerne med majsstivelse, krydderier og olie, så massen hænger sammen.",
            "Form små ovale hash browns med faste kanter.",
            "Steg dem 2-3 minutter på hver side i olie, eller bag dem i airfryer eller ovn, til de er gyldne og sprøde.",
            "Server straks, mens skorpen stadig er sprød.",
        ],
        nutrient_items=[("kartoffel", 400), ("majsstivelse", 10), ("rapsolie", 20)],
    ),
    Recipe(
        section="Tilbehør",
        title="Tzatziki",
        servings=4,
        finished_weight_g=380,
        ingredients=[
            "250 g græsk yoghurt 10 %",
            "200 g agurk, groftrevet og afdryppet",
            "1-2 fed hvidløg, fintrevet",
            "1 spsk olivenolie",
            "1 tsk citronsaft eller hvidvinseddike",
            "Salt, evt. lidt hakket dild eller mynte",
        ],
        method=[
            "Riv agurken groft, og pres så meget væde ud som muligt.",
            "Rør yoghurt sammen med agurk, hvidløg, olie og citronsaft.",
            "Smag til med salt og eventuelt dild eller mynte.",
            "Sæt tzatzikien på køl mindst 30 minutter før servering, så smagen samler sig.",
        ],
        nutrient_items=[
            ("græsk_yoghurt_10", 250),
            ("agurk", 200),
            ("hvidløg", 6),
            ("olivenolie", 14),
            ("citron", 5),
        ],
    ),
    Recipe(
        section="Aftensmad",
        title="Galetter med skinke, ost og æg",
        servings=4,
        finished_weight_g=950,
        ingredients=[
            "2 dl boghvedemel",
            "2 æg",
            "3 dl mælk",
            "1/2 tsk fint salt",
            "4 tsk smør til stegning",
            "4 skiver cheddar eller mozzarella",
            "8 skiver parmaskinke",
            "4 æg",
            "50 g frisk spinat",
        ],
        method=[
            "Pisk boghvedemel, æg, mælk og salt sammen til en glat dej uden klumper.",
            "Varm en pande op ved middel varme, smelt lidt smør, og fordel cirka 1/2 dl dej i et tyndt lag.",
            "Steg galetterne let gyldne på begge sider, og læg dem til side under et viskestykke, så de holder sig bløde.",
            "Læg en skive ost i midten af hver galette, og placér 2 skiver parmaskinke ovenpå.",
            "Fold kanterne let ind mod midten, så der dannes en lille fordybning til ægget.",
            "Slå 1 æg ud i hver galette, læg låg på panden, og steg ved lav varme i cirka 5 minutter, til hviden har sat sig.",
            "Server straks med frisk spinat ved siden af.",
        ],
        nutrient_items=[
            ("boghvedemel", 120),
            ("æg", 330),
            ("mælk_15", 300),
            ("smør", 20),
            ("mozzarella", 80),
            ("parmaskinke", 120),
            ("spinat", 50),
        ],
    ),
    Recipe(
        section="Aftensmad",
        title="Bergensk fiskesuppe",
        servings=2,
        finished_weight_g=1400,
        ingredients=[
            "500 g hvid fisk i mundrette stykker",
            "500 g urensede rejer",
            "2 stilke bladselleri",
            "2 gulerødder",
            "3 skalotteløg",
            "2 fed hvidløg",
            "6 dl fiskekraft",
            "2,5 dl blåmuslingekraft",
            "2 spsk olivenolie",
            "1,5 dl hvidvin",
            "2 æggeblommer",
            "1 dl fløde eller sæterømme",
            "Salt, peber og evt. cayenne",
        ],
        method=[
            "Pil rejerne. Skær grøntsagerne fint, og skær fisken i mundrette stykker.",
            "Sautér bladselleri, gulerødder, skalotteløg og hvidløg i olivenolie i cirka 10 minutter uden at de tager farve.",
            "Tilsæt hvidvin, og lad den koge ind, til smagen bliver koncentreret.",
            "Bring en del af fiskekraften til lige under kogepunktet, og pocher fisken forsigtigt 1-2 minutter. Tag den op, så den ikke overtilberedes.",
            "Varm resten af fiskekraften og blåmuslingekraften op i en gryde.",
            "Pisk æggeblommer og fløde sammen. Temperér blandingen med lidt af den varme kraft, og hæld den derefter tilbage i gryden.",
            "Varm suppen op uden at koge, til den er let cremet. Smag til med salt, peber og eventuelt lidt cayenne.",
            "Fordel grøntsager, fisk og rejer i tallerkener, og hæld den varme suppe over ved servering.",
        ],
        nutrient_items=[
            ("hvid_fisk", 500),
            ("rejer", 250),
            ("bladselleri", 80),
            ("gulerod", 140),
            ("skalotteløg", 90),
            ("hvidløg", 8),
            ("fiskekraft", 850),
            ("olivenolie", 28),
            ("hvidvin", 150),
            ("æg", 34),
            ("fløde_38", 100),
            ("blåmuslinger", 100),
        ],
    ),
    Recipe(
        section="Aftensmad",
        title="Boller i karry med grønt",
        servings=4,
        finished_weight_g=1800,
        ingredients=[
            ":: Kødboller",
            "400 g hakket kylling eller svinekød",
            "1 løg, finthakket",
            "1 æg",
            "1 dl mælk",
            "3 spsk havregryn",
            "Salt og peber",
            ":: Sauce og tilbehør",
            "2 spsk olie",
            "2 spsk karry",
            "1 løg",
            "2 gulerødder",
            "1 æble",
            "1-2 fed hvidløg",
            "1-2 spsk hvedemel",
            "6 dl bouillon",
            "1 dl mælk eller fløde",
            "280 g ris, tørvægt",
        ],
        method=[
            ":: Kødboller",
            "Rør farsen sammen med finthakket løg, æg, mælk, havregryn, salt og peber. Lad farsen hvile 15 minutter.",
            "Form farsen til boller med en ske, og kog dem i letsaltet vand i 8-10 minutter. Gem kogevandet til saucen.",
            ":: Sauce og servering",
            "Svits løg, gulerødder, æble og hvidløg i olie et par minutter. Tilsæt karry, og lad den kort stege med.",
            "Rør hvedemelet i, og spæd gradvist med bouillon, til saucen er glat.",
            "Lad saucen simre, til grøntsagerne er helt møre, og blend den derefter glat.",
            "Tilsæt mælk eller fløde, smag til, og læg kødbollerne tilbage i saucen.",
            "Kog risene efter pakkens anvisning, og server dem til retten.",
        ],
        nutrient_items=[
            ("hakket_kylling", 400),
            ("løg", 200),
            ("æg", 55),
            ("mælk_15", 200),
            ("havregryn", 30),
            ("rapsolie", 28),
            ("gulerod", 150),
            ("hvidløg", 6),
            ("hvedemel", 20),
            ("æble", 120),
            ("ris_tør", 280),
        ],
    ),
    Recipe(
        section="Aftensmad",
        title="Cottage pie, klassisk",
        servings=4,
        finished_weight_g=2200,
        ingredients=[
            "500 g hakket oksekød, 8-12 %",
            "1 stort løg",
            "2 gulerødder",
            "2 fed hvidløg",
            "2 spsk tomatpuré",
            "2 spsk hvedemel",
            "2,5 dl oksebouillon",
            "1 dl rødvin eller ekstra bouillon",
            "1 spsk Worcestershire sauce",
            "1 tsk tørret timian",
            "1 laurbærblad",
            "1 spsk olie",
            "Kartoffelmos: 1 kg kartofler, 50 g smør, 1-1,5 dl mælk",
            "Evt. 50 g cheddar",
        ],
        method=[
            "Skræl kartoflerne, og kog dem møre i letsaltet vand 15-20 minutter. Hæld vandet fra, og damp dem tørre.",
            "Mos kartoflerne med smør og varm mælk, og smag til med salt og peber.",
            "Sautér løg og gulerødder i olie i 5 minutter. Tilsæt hvidløg kort.",
            "Brun oksekødet grundigt. Tilsæt tomatpuré, og lad den stege med 1 minut.",
            "Rør hvedemelet i, og spæd med bouillon og rødvin lidt ad gangen.",
            "Tilsæt Worcestershire sauce, timian og laurbærblad, og lad fyldet simre 10-15 minutter til en tyk sovs.",
            "Fordel kødfyldet i et ovnfast fad. Læg kartoffelmosen over, og lav riller med en gaffel. Drys eventuelt med cheddar.",
            "Bag ved 200 °C i 20-25 minutter, til toppen er gylden. Lad retten hvile 10 minutter før servering.",
        ],
        nutrient_items=[
            ("oksekød_10", 500),
            ("løg", 150),
            ("gulerod", 200),
            ("hvidløg", 8),
            ("tomatpuré", 30),
            ("hvedemel", 16),
            ("rødvin", 100),
            ("worcestershire", 15),
            ("rapsolie", 14),
            ("kartoffel", 1000),
            ("smør", 50),
            ("mælk_35", 150),
            ("cheddar", 50),
        ],
    ),
    Recipe(
        section="Aftensmad",
        title="Cottage pie, sundere",
        servings=4,
        finished_weight_g=2300,
        ingredients=[
            "500 g hakket oksekød, 5 %",
            "1 løg",
            "2 gulerødder",
            "1 rød peberfrugt",
            "150 g champignon",
            "2 fed hvidløg",
            "2 spsk tomatpuré",
            "2,5 dl fedtfattig bouillon",
            "1 spsk Worcestershire sauce",
            "1 tsk olie",
            "Mos: 800 g kartofler og 300 g blomkål",
            "2 spsk skyr og 1-2 spsk letmælk",
        ],
        method=[
            "Kog kartofler og blomkål møre i samme gryde. Hæld vandet fra, og mos med skyr og lidt mælk.",
            "Sautér løg, gulerødder, peberfrugt og champignon i lidt olie, til grøntsagerne falder sammen.",
            "Tilsæt oksekødet, og brun det godt af.",
            "Rør tomatpuré i, spæd med bouillon, og tilsæt Worcestershire sauce.",
            "Lad fyldet simre 12-15 minutter, til det er samlet og saftigt.",
            "Fordel fyldet i et ovnfast fad, læg mosen over, og bag 20-25 minutter ved 200 °C.",
        ],
        nutrient_items=[
            ("oksekød_5", 500),
            ("løg", 120),
            ("gulerod", 150),
            ("peberfrugt", 150),
            ("champignon", 150),
            ("hvidløg", 8),
            ("tomatpuré", 30),
            ("worcestershire", 15),
            ("rapsolie", 5),
            ("kartoffel", 800),
            ("blomkål", 300),
            ("skyr", 30),
            ("mælk_15", 30),
        ],
    ),
    Recipe(
        section="Aftensmad",
        title="Hjemmelavet lasagne",
        servings=4,
        finished_weight_g=1900,
        ingredients=[
            "500 g hakket oksekød",
            "1 løg",
            "2 fed hvidløg",
            "2 gulerødder",
            "2 spsk tomatpuré",
            "400 g hakkede tomater",
            "1 dl vand eller bouillon",
            "1 tsk oregano",
            "1 tsk basilikum",
            "1 spsk olivenolie",
            "Bechamel: 40 g smør, 40 g hvedemel, 6 dl mælk",
            "10-12 lasagneplader, cirka 250 g",
            "120 g revet ost",
        ],
        method=[
            "Svits finthakket løg og hvidløg i olien, og brun derefter oksekødet grundigt.",
            "Tilsæt gulerødder, tomatpuré, hakkede tomater, vand og krydderier. Lad kødsaucen simre 25 minutter.",
            "Smelt smørret til bechamel, pisk hvedemelet i, og spæd med mælk lidt ad gangen, til saucen er glat og tyk.",
            "Læg lasagnen i lag med kødsauce, lasagneplader og bechamel. Gentag til fadet er fyldt.",
            "Slut med bechamel og revet ost på toppen.",
            "Bag ved 200 °C i 30-35 minutter, til overfladen er gylden. Lad lasagnen hvile 10 minutter før servering.",
        ],
        nutrient_items=[
            ("oksekød_10", 500),
            ("løg", 120),
            ("hvidløg", 8),
            ("gulerod", 150),
            ("tomatpuré", 30),
            ("hakkede_tomater", 400),
            ("oregano", 1),
            ("basilikum", 1),
            ("olivenolie", 14),
            ("smør", 40),
            ("hvedemel", 40),
            ("mælk_35", 600),
            ("lasagneplader", 250),
            ("mozzarella", 120),
        ],
    ),
    Recipe(
        section="Aftensmad",
        title="Hvid fisk med spinat og mornaysauce",
        servings=3,
        finished_weight_g=900,
        ingredients=[
            "450 g hvid fisk, fx torsk, kuller eller sej",
            "200 g frisk spinat eller optøet, afdryppet spinat",
            "2 dl mornaysauce",
            "Smør til fadet",
            "Salt, peber og lidt citronsaft",
            "Evt. 30 g revet ost",
        ],
        method=[
            "Forvarm ovnen til 200 °C, og smør et ovnfast fad let.",
            "Krydr fisken med salt, peber og citronsaft.",
            "Fordel spinaten i bunden af fadet, læg fisken ovenpå, og hæld mornaysaucen over.",
            "Drys eventuelt lidt ost på toppen.",
            "Bag retten 20-25 minutter, til fisken netop flager og saucen bobler langs kanten.",
            "Server med kogte kartofler, ris eller kartoffelmos.",
        ],
        nutrient_items=[("hvid_fisk", 450), ("spinat", 200), ("mornaysauce", 200), ("mozzarella", 30)],
    ),
    Recipe(
        section="Aftensmad",
        title="Pastarør med østershatte og fløde",
        servings=3,
        finished_weight_g=1000,
        ingredients=[
            "250 g pastarør, fx rigatoni eller penne",
            "250 g østershatte",
            "3 skalotteløg",
            "2 fed hvidløg",
            "2 spsk smør",
            "1 spsk olivenolie",
            "2 dl piskefløde",
            "1/2 dl hvidvin, valgfrit",
            "1 tsk citronsaft",
            "50 g revet parmesan",
            "Frisk persille, salt og peber",
        ],
        method=[
            "Kog pastaen al dente i rigeligt saltet vand, og gem lidt af kogevandet.",
            "Sautér finthakkede skalotteløg og hvidløg i smør og olivenolie, til de er bløde og søde.",
            "Tilsæt østershattene, og steg dem ved god varme, til de er gyldne og let sprøde i kanterne.",
            "Hæld hvidvin på, hvis du bruger den, og lad den koge let ind.",
            "Tilsæt fløde, og lad saucen simre 5-7 minutter. Smag til med citronsaft, salt og peber.",
            "Vend pastaen i saucen, og justér konsistensen med lidt kogevand.",
            "Server med parmesan og frisk persille.",
        ],
        nutrient_items=[
            ("pasta_tør", 250),
            ("østershatte", 250),
            ("skalotteløg", 90),
            ("hvidløg", 8),
            ("smør", 28),
            ("olivenolie", 14),
            ("fløde_38", 200),
            ("hvidvin", 50),
            ("parmesan", 50),
        ],
    ),
    Recipe(
        section="Aftensmad",
        title="Proteinrig pastaret med oksekød",
        servings=4,
        finished_weight_g=1650,
        ingredients=[
            "400 g hakket oksekød, 4-7 %",
            "200 g fusilli",
            "250 g hytteost 1,5 %",
            "420 g pastasauce",
            "100 g frisk spinat",
            "50 g parmesan",
            "50 g revet ost 13 %",
            "1 tsk oregano",
            "1 tsk hvidløgspulver",
            "1 tsk løgpulver",
            "1 tsk sort peber",
            "1 tsk salt",
        ],
        method=[
            "Kog pastaen efter anvisningen, så den stadig har bid, og lad den dryppe godt af.",
            "Brun oksekødet grundigt på en varm pande, og krydr med oregano, hvidløgspulver, løgpulver, peber og salt.",
            "Bland pasta, oksekød, spinat, hytteost og pastasauce i et ovnfast fad.",
            "Fordel parmesan og revet ost på toppen.",
            "Bag ved 200 °C i 10-15 minutter, til retten er gennemvarm og osten er smeltet.",
        ],
        nutrient_items=[
            ("oksekød_5", 400),
            ("pasta_tør", 200),
            ("hytteost", 250),
            ("hakkede_tomater", 420),
            ("spinat", 100),
            ("parmesan", 50),
            ("revet_ost_13", 50),
            ("oregano", 2),
        ],
    ),
    Recipe(
        section="Aftensmad",
        title="Spicy Mac & Cheese",
        servings=5,
        finished_weight_g=2015,
        ingredients=[
            ":: Kød og pasta",
            "500 g hakket oksekød, 4-7 %",
            "350 g suppehorn (pasta)",
            "10 g oksebouillon (terning)",
            "6 dl kogende vand",
            ":: Ost og mejeri",
            "100 g revet ost",
            "50 g flødeost med hvidløg og urter",
            "200 g minimælk",
            "2 skiver cheddar (ca. 40 g)",
            ":: Grøntsager og smag",
            "100 g rødløg, hakket",
            "40 g tomatpuré",
            ":: Krydderier",
            "Salt",
            "Sort peber",
            "Løgpulver",
            "Cayennepeber",
            "Paprika",
        ],
        method=[
            ":: Kød og løg",
            "Brun oksekødet i en stor gryde ved høj varme, til det er gennemstegt og let karamelliseret.",
            "Tilsæt hakket rødløg og svits ved middel varme, til løget er blødt og let gyldent.",
            "Krydr med salt, sort peber, løgpulver, paprika og cayennepeber, og rør det godt sammen.",
            ":: Sauce og pasta",
            "Lav et lille hul i midten af gryden og tilsæt tomatpuréen. Lad den stege i 1-2 minutter, så den mister sin råsmag.",
            "Hæld kogende vand, oksebouillon og minimælk i gryden, og rør det hele godt sammen.",
            "Tilsæt suppehornene direkte i gryden. Lad retten simre ved middel varme i 12-15 minutter under jævnlig omrøring, indtil pastaen er mør og det meste af væsken er absorberet.",
            ":: Afslutning",
            "Skru ned for varmen og rør flødeost, revet ost og cheddar i, til retten er ensartet og cremet. Smag til med salt, peber og cayennepeber.",
        ],
        nutrient_items=[
            ("oksekød_5", 500),
            ("pasta_tør", 350),
            ("revet_ost_13", 100),
            ("flødeost_urter", 50),
            ("minimælk", 200),
            ("løg", 100),
            ("tomatpuré", 40),
            ("cheddar", 40),
        ],
    ),
    Recipe(
        section="Aftensmad",
        title="Frikadeller",
        servings=4,
        finished_weight_g=680,
        ingredients=[
            "500 g hakket svinekød",
            "1 løg, revet eller meget fint hakket",
            "1 æg",
            "2 spsk hvedemel",
            "1 dl mælk eller danskvand",
            "1-2 tsk salt",
            "Friskkværnet peber",
            "Smør til stegning",
        ],
        method=[
            "Rør først det hakkede svinekød sejt med salt, til farsen bliver blank og binder tydeligt, før de øvrige ingredienser tilsættes.",
            "Tilsæt løget, som gerne må være revet i foodprocessor for den bedste konsistens, og rør det godt ind i farsen.",
            "Rør æg, hvedemel, mælk eller danskvand og peber i, til farsen er lind og ensartet.",
            "Lad farsen hvile 10 minutter, så den samler sig.",
            "Prøvesteg en lille frikadelle og smag, om farsen er tilpas saltet. Juster eventuelt krydringen, før resten steges.",
            "Form små frikadeller med en ske eller fugtige hænder.",
            "Steg frikadellerne i smør på en pande ved middel varme i 4-5 minutter på hver side, til de er gyldne og gennemstegte.",
        ],
        nutrient_items=[
            ("hakket_svin", 500),
            ("løg", 100),
            ("æg", 55),
            ("hvedemel", 20),
            ("vand", 100),
            ("smør", 10),
        ],
    ),
    Recipe(
        section="Aftensmad",
        title="Karrymillionbøf med kartoffelmos",
        servings=5,
        finished_weight_g=2450,
        ingredients=[
            ":: Karrymillionbøf",
            "400 g hakket svinekød 10 %",
            "2 store løg (ca. 200 g)",
            "2 store gulerødder (ca. 200 g)",
            "3 tsk karry",
            "3 tsk majsstivelse",
            "4 dl vand",
            "1 bouillonterning eller 2 tsk bouillonpasta",
            "Salt",
            ":: Kartoffelmos",
            "1 kg kartofler",
            "1-2 dl skummet- eller minimælk",
            "Salt og peber",
            ":: Tilbehør",
            "500 g frisk ananas i stykker",
            "Evt. 2 spsk hakket frisk koriander eller persille",
        ],
        method=[
            ":: Karrymillionbøf",
            "Brun kødet i en gryde uden ekstra fedtstof, til det smuldrer og tager farve.",
            "Hak løgene fint og riv gulerødderne groft. Svits dem sammen med kødet i 3-4 minutter.",
            "Rør karryen i kødet, så krydderiet varmes godt igennem.",
            "Rør majsstivelsen ud i vandet, og hæld blandingen i gryden sammen med bouillonen. Kog op under omrøring.",
            "Lad retten simre i 10 minutter, og smag til med salt.",
            ":: Kartoffelmos",
            "Skræl kartoflerne, skær dem i mindre stykker og kog dem møre i letsaltet vand.",
            "Hæld vandet fra og mos kartoflerne med en kartoffelmoser eller et piskeris.",
            "Spæd med lun mælk, til mosen er blød og luftig. Smag til med salt og peber.",
            ":: Tilbehør og servering",
            "Skær ananassen i mundrette stykker.",
            "Server karrymillionbøffen med kartoffelmos, ananas og eventuelt hakket koriander eller persille.",
        ],
        nutrient_items=[
            ("hakket_svin_10", 400),
            ("løg", 200),
            ("gulerod", 200),
            ("majsstivelse", 9),
            ("vand", 400),
            ("kartoffel", 1000),
            ("minimælk", 150),
            ("ananas", 500),
        ],
    ),
    Recipe(
        section="Aftensmad",
        title="One pot kylling i karry",
        servings=2,
        finished_weight_g=870,
        ingredients=[
            "450 g kyllingebryst",
            "3 tsk karry",
            "1/2 tsk paprika",
            "1 spsk sukker",
            "1/2 tsk stødt spidskommen",
            "400 ml kokosmælk",
            "1 hønsebouillonterning",
            "160 g ris",
            "Frisk persille til servering",
            "Salt og peber",
        ],
        method=[
            "Fjern eventuelle sener fra kyllingen.",
            "Læg kyllingebrysterne hele i en gryde sammen med karry, paprika, sukker, spidskommen, kokosmælk og bouillonterning. Rør rundt.",
            "Tilsæt risene direkte i gryden og rør rundt igen.",
            "Sæt låget på med en lille sprække til damp, og lad retten simre ved middel varme i 30 minutter.",
            "Tag gryden af varmen og brug to gafler til at rive kyllingen i strimler.",
            "Sæt gryden tilbage på blusset i 5 minutter og lad det boble let op. Smag til med salt og peber.",
            "Server med frisk persille.",
        ],
        nutrient_items=[
            ("kyllingebryst", 450),
            ("ris_tør", 160),
            ("kokosmælk", 400),
            ("sukker", 12),
        ],
    ),
    Recipe(
        section="Aftensmad",
        title="Stroganoff (okse)",
        servings=4,
        finished_weight_g=1300,
        ingredients=[
            ":: Kød og base",
            "600 g oksekød i tern eller strimler",
            "150 g bacon i tern",
            "2 løg i tern",
            "2 spsk smør",
            ":: Sauce",
            "50 g tomatpuré",
            "3 dl piskefløde",
            "2 tsk paprika",
            "Salt og peber",
        ],
        method=[
            ":: Klargøring",
            "Skær løg og bacon i tern. Skær oksekødet i mindre tern eller strimler, hvis stykkerne er store.",
            ":: Stegning og sauce",
            "Brun løgene i smør på en stor pande eller i en gryde, og tag dem derefter af panden.",
            "Brun baconen, til den tager let farve, og tag den af panden.",
            "Brun oksekødet grundigt i panden. Tilsæt tomatpuréen, og lad den stege med kødet i 1 minut.",
            "Kom løg og bacon tilbage i panden. Hæld fløden over og tilsæt paprika.",
            "Lad retten koge igennem ved lav varme i 5-10 minutter, til saucen samler sig. Smag til med salt og peber, og server straks.",
        ],
        nutrient_items=[
            ("oksekød_10", 600),
            ("bacon", 150),
            ("løg", 200),
            ("smør", 28),
            ("tomatpuré", 50),
            ("fløde_38", 300),
            ("paprika", 6),
        ],
    ),
    Recipe(
        section="Weekend",
        title="Aligot",
        servings=4,
        finished_weight_g=1650,
        ingredients=[
            "1 kg melede kartofler",
            "2 fed hvidløg, valgfrit",
            "50 g smør",
            "2,5 dl varm fløde",
            "350 g Tommes de Savoir",
            "Salt og hvid peber",
        ],
        method=[
            "Kog kartoflerne møre i letsaltet vand, eventuelt sammen med hvidløget. Hæld vandet fra, og damp dem tørre.",
            "Mos kartoflerne helt glatte, og rør smørret i ved lav varme.",
            "Spæd med den varme fløde lidt ad gangen, til mosen er glat og tyk.",
            "Tilsæt osten gradvist under konstant omrøring, så massen bliver blank og elastisk.",
            "Fortsæt, til aligot kan trækkes i lange tråde.",
            "Smag til med salt og hvid peber, og server straks.",
        ],
        nutrient_items=[("kartoffel", 1000), ("hvidløg", 6), ("smør", 50), ("fløde_38", 250), ("tommes_de_savoir", 350)],
    ),
    Recipe(
        section="Weekend",
        title="Langtidsstegt and",
        servings=6,
        finished_weight_g=2100,
        ingredients=[
            "1 and på ca. 3,5 kg",
            "Salt og peber",
            "Evt. æbler og svesker til fyld",
        ],
        method=[
            "Dup anden tør, og krydr den godt både indvendigt og udvendigt med salt og peber.",
            "Steg anden ved 150 °C i cirka 3-3,5 timer, svarende til omtrent 50-60 minutter pr. kilo.",
            "Mål kernetemperaturen i låret; den bør være omkring 75 °C.",
            "Hæv eventuelt ovntemperaturen til 220-230 °C de sidste 10-15 minutter, hvis skindet skal være ekstra sprødt.",
            "Lad anden hvile 15-20 minutter før udskæring.",
        ],
        nutrient_items=[("and", 2100)],
    ),
    Recipe(
        section="Weekend",
        title="Pulled pork",
        servings=8,
        finished_weight_g=1900,
        ingredients=[
            "2 kg svinenakke",
            "2 spsk paprika",
            "1 spsk brun farin",
            "1 spsk salt",
            "1 tsk peber",
            "1 tsk chilipulver",
            "1 tsk hvidløgspulver",
            "1 tsk løgpulver",
            "1 dl æblecidereddike",
            "1 dl æblejuice eller vand",
            "BBQ-sauce efter smag",
        ],
        method=[
            "Bland krydderierne, og gnid blandingen grundigt ind i kødet.",
            "Læg kødet i stegeso eller et ovnfast fad, og tilsæt æblecidereddike og æblejuice.",
            "Steg ved 110-120 °C i 6-8 timer, til kødet er så mørt, at det let kan trækkes fra hinanden.",
            "Lad kødet hvile 20 minutter, og trevl det derefter med to gafler.",
            "Vend eventuelt kødet med lidt BBQ-sauce lige før servering.",
        ],
        nutrient_items=[("svinenakke", 2000), ("brun_farin", 15), ("cidereddike", 100), ("æblejuice", 100)],
    ),
]

COMPONENT_RULES = {
    "Brød i stegeso": {
        "ingredients": [("Dej", 0, 4)],
        "method": [("Dej", 0, 2), ("Bagning", 2, 7)],
    },
    "Kanelsnegle": {
        "ingredients": [("Dej", 0, 7), ("Fyld", 7, 8), ("Glasur", 8, 9)],
        "method": [("Dej", 0, 3), ("Fyld og formning", 3, 6), ("Bagning", 6, 7)],
    },
    "Surdejsbrød": {
        "ingredients": [("Dej", 0, 6), ("Klargøring", 6, 7)],
        "method": [("Dej", 0, 3), ("Foldning og hævning", 3, 6), ("Bagning", 6, 9)],
    },
    "Rugbrød": {
        "ingredients": [("Dag 1", 0, 7), ("Dag 2", 7, 11), ("Bagning", 11, 12)],
        "method": [("Dag 1", 0, 3), ("Dag 2", 3, 6), ("Formning og hævning", 6, 8), ("Bagning", 8, 10)],
    },
    "Mini hash browns": {
        "ingredients": [("Kartoffelmasse", 0, 7)],
        "method": [("Forberedelse", 0, 2), ("Formning og stegning", 2, 5)],
    },
    "Tzatziki": {
        "ingredients": [("Tzatziki", 0, 6)],
        "method": [("Tzatziki", 0, 4)],
    },
    "Galetter med skinke, ost og æg": {
        "ingredients": [("Galettedej", 0, 5), ("Skinkefyld", 5, 8), ("Til servering", 8, 9)],
        "method": [("Galetter", 0, 3), ("Skinkefyld", 3, 6), ("Servering", 6, 7)],
    },
    "Bergensk fiskesuppe": {
        "ingredients": [("Suppebase", 0, 10), ("Legering og finish", 10, 13)],
        "method": [("Forberedelse", 0, 1), ("Suppebase", 1, 5), ("Legering", 5, 7), ("Servering", 7, 8)],
    },
    "Boller i karry med grønt": {
        "ingredients": [("Boller", 0, 6), ("Sovs", 6, 11), ("Til servering", 11, 12)],
        "method": [("Boller", 0, 2), ("Sovs", 2, 6), ("Til servering", 6, 7)],
    },
    "Cottage pie, klassisk": {
        "ingredients": [("Fyld", 0, 12), ("Kartoffelmos og top", 12, 14)],
        "method": [("Kartoffelmos", 0, 2), ("Fyld", 2, 6), ("Samling og bagning", 6, 8)],
    },
    "Cottage pie, sundere": {
        "ingredients": [("Fyld", 0, 10), ("Mos", 10, 12)],
        "method": [("Mos", 0, 1), ("Fyld", 1, 5), ("Samling og bagning", 5, 6)],
    },
    "Hjemmelavet lasagne": {
        "ingredients": [("Kødsauce", 0, 10), ("Bechamel", 10, 11), ("Samling", 11, 13)],
        "method": [("Kødsauce", 0, 2), ("Bechamel", 2, 3), ("Samling og bagning", 3, 6)],
    },
    "Hvid fisk med spinat og mornaysauce": {
        "ingredients": [("Fiskefad", 0, 6)],
        "method": [("Fiskefad", 0, 6)],
    },
    "Pastarør med østershatte og fløde": {
        "ingredients": [("Pasta og sauce", 0, 11)],
        "method": [("Pasta", 0, 1), ("Sauce", 1, 5), ("Samling", 5, 7)],
    },
    "Proteinrig pastaret med oksekød": {
        "ingredients": [("Pastaret", 0, 12)],
        "method": [("Pasta og kød", 0, 2), ("Samling og bagning", 2, 5)],
    },
    "Aligot": {
        "ingredients": [("Aligot", 0, 6)],
        "method": [("Kartoffelmos", 0, 3), ("Ost og finish", 3, 6)],
    },
    "Langtidsstegt and": {
        "ingredients": [("And", 0, 3)],
        "method": [("Stegning", 0, 5)],
    },
    "Pulled pork": {
        "ingredients": [("Kød og krydderier", 0, 10), ("Servering", 10, 11)],
        "method": [("Klargøring", 0, 2), ("Langtidstilberedning", 2, 4), ("Afslutning", 4, 5)],
    },
}
